### ISSUE TITLE
Incorrect working grid_search.

### ISSUE THREAD

**Issue by YourPersonalFear** [PacktPublishing/Artificial-Intelligence-with-Python#21]
I getting equal results with with using recall_weighted and precision_weighted scorers. What can I do for fix it and get results as in a book? Links for mine and original codes below.
[My code](https://pastebin.com/XbU3ZutM) , [Original code](https://github.com/PacktPublishing/Artificial-Intelligence-with-Python/blob/master/Chapter%2003/code/run_grid_search.py)

Ty u all

**Comment by YourPersonalFear** [comment]
And tell me please - how working a GridSearchCV with parameters_grid and metrics

**Comment by sonam-packt** [comment]
Hi @YourPersonalFear,

Here is the new edition of the book which has updated code in it, kindly check this one https://www.packtpub.com/product/artificial-intelligence-with-python-second-edition/9781839219535 

Thank you1
