### ISSUE TITLE
missing preprocessing.py

### ISSUE THREAD

**Issue by invegat** [PacktPublishing/Artificial-Intelligence-with-Python#4]
There is no preprocessing.py in "Chapter 02" or any other chapters of the downloaded code.  In the Safari Books Online ebook at the end of chapter 2 [Preprocessing data]: "The code for this entire section is given in the preprocessing.py file."

**Comment by Ieatdedbabies** [comment]
hi, you can import preprocessing from sklearn. to install sklearn you can use pip in terminal:

pip install sklearn

and then in your python file:

from sklearn import preprocessing

**Comment by invegat** [comment]
Thanks!
