### ISSUE TITLE
Chapter 6 - Virginia is not in Costal States

### ISSUE THREAD

**Issue by danibrear** [PacktPublishing/Artificial-Intelligence-with-Python#6]
In your map, the eastern shore of Virginia is incorrectly attributed to Maryland and Virginia is not listed as a Costal State. This is incorrect.
<img width="260" alt="screen shot 2018-01-25 at 9 57 40 am" src="https://user-images.githubusercontent.com/1081640/35394641-410cc3fc-01b6-11e8-94f4-4b42c5901222.png">

**Comment by sarvesh-packt** [comment]
Please reopen if the issue still persists.
