### ISSUE TITLE
No module named 'utilities'

### ISSUE THREAD

**Issue by cleanbyrd** [PacktPublishing/Artificial-Intelligence-with-Python#7]
I am attempting Logistic Regression classifier.  I'm in Spyder/Anaconda so I can edit.  I get error: no module named 'utilities'.  What's wrong?

**Comment by JeremyMCastillo** [comment]
You need to download the utilities.py file from the Chapter 02/code directory in the repo and put it in the same directory as your Logistic Regression script.

**Comment by cleanbyrd** [comment]
Thanks for the responses!

**Comment by diemgomez** [comment]
@JeremyMCastillo  I did what you mention, but it still doesn't work. Can you please help me
