### ISSUE TITLE
 from utilities import visualize_classifier 

### ISSUE THREAD

**Issue by cleanbyrd** [PacktPublishing/Artificial-Intelligence-with-Python#8]
This is not working.   The entire book is based on line 5, so I cannot proceed.  Utilities module does not exist. Can someone please tell me what's wrong?

**Comment by sabya786** [comment]
Hi,
Take the utilities.py from chapter-2 code and put in your python 35 lib
and import it

**Comment by asghar3166** [comment]
Hi,
Use (from pkgutil import extend_path) and run the code. It should work!

**Comment by asghar3166** [comment]
Building a Decision Tree classifier in Chapter 3

**Use the following below imports for "visualize_classifier" to work.**

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier


# Decision Trees classifier 
params = {'random_state': 0, 'max_depth': 4} 
classifier = DecisionTreeClassifier(**params) 
classifier.fit(X_train, y_train) 
visualize_classifier(classifier, X_train, y_train, 'Training dataset')

**Output**
![decision_tree_chp_3](https://user-images.githubusercontent.com/22902750/39660079-bb25239e-5005-11e8-9a69-d3a9d418b1f4.JPG)

**Comment by ghost** [comment]
which code of chapter 2 please explain or give the code @sabya786

**Comment by diemgomez** [comment]
Hi, I'm having the same problem and I try what @asghar3166  said, but it did not work. Can some help us please!!

`Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> import numpy as np
>>> from sklearn import linear_model
>>> import matplotlib.pyplot as plt
>>> from utilities import visualize_classifier
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    from utilities import visualize_classifier
ModuleNotFoundError: No module named 'utilities'
>>> from pkgutil import extend_path
>>> from utilities import visualize_classifier
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    from utilities import visualize_classifier
ModuleNotFoundError: No module named 'utilities'
`

**Comment by karant17** [comment]
Do use the following code in place of `from utilities import visualize_classifier` to achieve the output.
`def visualize_classifier(classifier, X, y):`
`    # Define the minimum and maximum values for X and Y`
`    # that will be used in the mesh grid`
    `    min_x, max_x = X[:, 0].min() - 1.0, X[:, 0].max() + 1.0`
    `   min_y, max_y = X[:, 1].min() - 1.0, X[:, 1].max() + 1.0`


Hope this helps you find the solution. 
You can find the code block in utilites.py file

**Comment by GeniusMehra** [comment]
You can just remove the line 'utilities import visualize_classifier'. Then it will work fine as we are defining function visualize_classifier later in the code

**Comment by pr0steg** [comment]
Apart from downgrading matplotlib to 3.5.3, you can disable File | Settings | Tools | Python Scientific | Show plots in tool window.
